apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "sia.fullname" . }}
  labels:
    app: {{ template "sia.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ template "sia.fullname" . }}
  selector:
    matchLabels:
      app: {{ template "sia.fullname" . }}
      release: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        app: {{ template "sia.fullname" . }}
        release: "{{ .Release.Name }}"
        {{- include "sia.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ template "sia.fullname" . }}
        image: "{{ .Values.repository }}:{{ .Values.imageTag }}"
        imagePullPolicy: {{ .Values.pullPolicy }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
        - name: SIA_DIR
          value: {{ .Values.siaServer.siaDir | quote }}
        - name: SIA_DATA_DIR
          value: {{ .Values.siaServer.siaDataDir | quote }}
        - name: SIAD_DATA_DIR
          value: {{ .Values.siaServer.siadDataDir | quote }}

        ports:
        - name: sia-1
          containerPort: {{ .Values.siaServer.serverPort | int }}
          protocol: TCP
        - name: sia-2
          containerPort: {{ .Values.siaServer.serverPort | int | add 1 }}
          protocol: TCP
        - name: sia-3
          containerPort: {{ .Values.siaServer.serverPort | int | add 2 }}
          protocol: TCP
        - name: sia-4
          containerPort: {{ .Values.siaServer.serverPort | int | add 3 }}
          protocol: TCP
        volumeMounts:
        - name: data-dir
          mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data-dir
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
